<<<<<<< HEAD
=======
 
>>>>>>> origin/v4
name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - v4
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
<<<<<<< HEAD
<<<<<<< HEAD
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14
=======
=======
>>>>>>> origin/v4
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 22
<<<<<<< HEAD
>>>>>>> origin/v4
=======
>>>>>>> origin/v4
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
<<<<<<< HEAD
<<<<<<< HEAD
        uses: actions/upload-pages-artifact@v2
=======
        uses: actions/upload-pages-artifact@v3
>>>>>>> origin/v4
=======
        uses: actions/upload-pages-artifact@v3
>>>>>>> origin/v4
        with:
          path: public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
<<<<<<< HEAD
<<<<<<< HEAD
        uses: actions/deploy-pages@v2
=======
        uses: actions/deploy-pages@v4
>>>>>>> origin/v4
=======
        uses: actions/deploy-pages@v4
>>>>>>> origin/v4
